name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          docker build -t priyankapathak92/cost:latest .
          docker save -o cost_image.tar priyankapathak92/cost:latest
        working-directory: ./  # Change this to your Dockerfile directory

      - name: Upload Docker Image Artifact
        uses: actions/upload-artifact@v2
        with:
          name: cost_image
          path: cost_image.tar

  publish:
    name: Continuous Delivery
    runs-on: ubuntu-latest

    needs: build  # Ensure the 'build' job is completed before starting this job

    steps:
      - name: Download Docker Image Artifact
        uses: actions/download-artifact@v2
        with:
          name: cost_image
          path: /tmp

      - name: Load Docker Image
        run: |
          docker load -i /tmp/cost_image.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker push priyankapathak92/cost:latest
